[workspace]
# Directories to type check
project-includes = ["src", "tests"]

# Platform to emulate
python-platform = "windows"

[errors]
bad-assignment = false
bad-return = false
bad-parameter = true
unused-variable = false

[features]
semantic-tokens = true
inlay-hints = true
type-checking = true
