# Project Title

data_ingestion:
  user_item_dataset_download_url: "https://mcauleylab.ucsd.edu/public_datasets/data/steam/australian_users_items.json.gz"
  steam_game_dataset_download_url: "https://cseweb.ucsd.edu/~wckang/steam_games.json.gz"
  raw_data_dir: "data/raw"

data_cleaning:
  root_dir: "data/processed"
  raw_data_dir: 'data/raw'

feature_engineering:
  root_dir: "data/processed"
  transformed_train_path: "data/processed/train.csv"
  transformed_test_path: "data/processed/test.csv"
  transformed_data_path: "data/processed/transformed_df.csv"